# Generated by Django 5.0.2 on 2024-02-21 17:04

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_alter_product_toprated'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='overview',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=11),
            preserve_default=False,
        ),
    ]
